name: generate-terraform-docs
# This workflow will generate terraform docs into README.md in the root, examples, and modules folders.
# Source: https://github.com/equinix-labs/terraform-equinix-kubernetes-addons/blob/main/.github/workflows/documentation.yaml

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tpl'
      - '**/*.tf'

jobs:
  tf-docs:
    name: TF docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        id: actions-checkout
        with:
          ref: main

      - name: Render Terraform docs inside the README.md files of examples
        id: terraform-docs-examples
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          config-file: templates/example-terraform-docs.yaml
          working-dir: examples
          recursive: true
          output-file: README.md
          args: --sort-by required
          indention: 2
          git-push: "false"

      - name: Render Terraform docs inside the README.md files of modules
        id: terraform-docs-modules
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          config-file: templates/modules-terraform-docs.yaml
          working-dir: modules
          recursive: true
          output-file: README.md
          args: --sort-by required
          indention: 2
          git-push: "false"

      - name: Replace EXAMPLE_PATH placeholders inside the README.md files of examples
        run: |
          find examples -name "README.md" | while read -r file; do
            dir_name=$(basename "$(dirname "$file")")
            sed -i "" "s@EXAMPLE_PATH@$dir_name@g" "$file"
            sed -i "" "s@\.\.\/\.\.@equinix\/fabric\/equinix\/@" "$file"
          done

      # terraform-docs/gh-actions@v1.0.0 modifies .git files with owner root:root, and the following steps fail with
      # insufficient permission for adding an object to repository database .git/objects
      # since the expected user is runner:docker. See https://github.com/terraform-docs/gh-actions/issues/90
      - name: Fix .git owner
        run: sudo chown runner:docker -R .git

      - name: Create Pull Request
        if: steps.terraform-docs.outputs.num_changed != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'generate-terraform-docs: automated action'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'generate-terraform-docs: automated action'
          body: |
            Update terraform docs
          branch-suffix: timestamp
          base: main
          signoff: true
          delete-branch: true

      # TODO(ocobleseqx): https://github.com/peter-evans/enable-pull-request-automerge
