name: terratests-prod-metal-nimf-suite

on:
  workflow_dispatch:

jobs:
  setup-tests:
    name: Setup NIMF DIGP Tests
    runs-on: ubuntu-latest
    env:
      TF_VAR_equinix_client_id: ${{ secrets.EQUINIX_CLIENT_ID }}
      TF_VAR_equinix_client_secret: ${{ secrets.EQUINIX_CLIENT_SECRET }}
      TF_VAR_metal_auth_token: ${{ secrets.METAL_AUTH_TOKEN }}
      GOOGLE_SERVICE_KEYS: ${{ secrets.GOOGLE_SERVICE_KEYS }}
      TEST_DATA_PROD_METAL_NIMF_2_AWS_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_AWS_CONNECTION }}
      TEST_DATA_PROD_METAL_NIMF_2_AZURE_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_AZURE_CONNECTION }}
      TEST_DATA_PROD_METAL_NIMF_2_ORACLE_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_ORACLE_CONNECTION }}
      TEST_DATA_PROD_CLOUD_ROUTER_2_METAL_NIMF_CONNECTION: ${{ secrets.TEST_DATA_PROD_CLOUD_ROUTER_2_METAL_NIMF_CONNECTION }}
      TEST_DATA_PROD_METAL_NIMF_2_PORT_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_PORT_CONNECTION }}
      TEST_DATA_PROD_METAL_NIMF_2_SERVICE_PROFILE_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_SERVICE_PROFILE_CONNECTION }}
      TEST_DATA_PROD_METAL_NIMF_2_GOOGLE_CONNECTION: ${{ secrets.TEST_DATA_PROD_METAL_NIMF_2_GOOGLE_CONNECTION }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
        id: go

      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get dependencies
        run: |
          go mod download
          go install github.com/thogarty/go-junit-report/v2@latest
          pip3 install junit2html

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Install jq
        run: |
            sudo apt-get install jq

      - name: Set Connection Name variable
        run: echo "TF_VAR_connection_name=nimf_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setup Variables Files
        run: |
          TIMESTAMP=$(date +"%m%d%M%S")
          SUFFIX="_DIGP" 
          echo $TEST_DATA_PROD_METAL_NIMF_2_AZURE_CONNECTION >> "./examples/metal-nimf-2-azure-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-azure-connection/terraform.tfvars.json > ./examples/metal-nimf-2-azure-connection/tmp.test.json && mv ./examples/metal-nimf-2-azure-connection/tmp.test.json ./examples/metal-nimf-2-azure-connection/terraform.tfvars.json
          echo $TEST_DATA_PROD_METAL_NIMF_2_AWS_CONNECTION >> "./examples/metal-nimf-2-aws-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-aws-connection/terraform.tfvars.json > ./examples/metal-nimf-2-aws-connection/tmp.test.json && mv ./examples/metal-nimf-2-aws-connection/tmp.test.json ./examples/metal-nimf-2-aws-connection/terraform.tfvars.json
          echo $TEST_DATA_PROD_METAL_NIMF_2_ORACLE_CONNECTION >> "./examples/metal-nimf-2-oracle-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-oracle-connection/terraform.tfvars.json > ./examples/metal-nimf-2-oracle-connection/tmp.test.json && mv ./examples/metal-nimf-2-oracle-connection/tmp.test.json ./examples/metal-nimf-2-oracle-connection/terraform.tfvars.json
          echo $TEST_DATA_PROD_CLOUD_ROUTER_2_METAL_NIMF_CONNECTION >> "./examples/cloud-router-2-metal-nimf-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/cloud-router-2-metal-nimf-connection/terraform.tfvars.json > ./examples/cloud-router-2-metal-nimf-connection/tmp.test.json && mv ./examples/cloud-router-2-metal-nimf-connection/tmp.test.json ./examples/cloud-router-2-metal-nimf-connection/terraform.tfvars.json
          echo $TEST_DATA_PROD_METAL_NIMF_2_PORT_CONNECTION >> "./examples/metal-nimf-2-port-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-port-connection/terraform.tfvars.json > ./examples/metal-nimf-2-port-connection/tmp.test.json && mv ./examples/metal-nimf-2-port-connection/tmp.test.json ./examples/metal-nimf-2-port-connection/terraform.tfvars.json
          echo $TEST_DATA_PROD_METAL_NIMF_2_SERVICE_PROFILE_CONNECTION >> "./examples/metal-nimf-2-service-profile-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-service-profile-connection/terraform.tfvars.json > ./examples/metal-nimf-2-service-profile-connection/tmp.test.json && mv ./examples/metal-nimf-2-service-profile-connection/tmp.test.json ./examples/metal-nimf-2-service-profile-connection/terraform.tfvars.json
          echo $GOOGLE_SERVICE_KEYS >> "./examples/metal-nimf-2-google-connection/keys.json"
          echo $TEST_DATA_PROD_METAL_NIMF_2_GOOGLE_CONNECTION >> "./examples/metal-nimf-2-google-connection/terraform.tfvars.json"
          jq --arg timestamp "$TIMESTAMP" '.connection_name = ($timestamp + "_" + .connection_name)' ./examples/metal-nimf-2-google-connection/terraform.tfvars.json > ./examples/metal-nimf-2-google-connection/tmp.test.json && mv ./examples/metal-nimf-2-google-connection/tmp.test.json ./examples/metal-nimf-2-google-connection/terraform.tfvars.json

      - name: Run Go Tests
        run:
          go test ./tests/prod/metal-nimf -v -json -count 1 -parallel 8 -timeout 180m | tee metal_prod_suite.log

      - name: Create HTML Testing Report
        run: |
          go-junit-report -parser gojson -in metal_prod_suite.log  > metal_prod_suite.xml && python3 -m junit2htmlreport metal_prod_suite.xml metal_prod_suite.html

      - name: Upload HTML Testing Report
        uses: actions/upload-artifact@v4
        with:
          name: Metal NIMF Prod Suite Terraform Modules Testing Report
          path: metal_prod_suite.html
          compression-level: 0
